apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  DATABASE_URI: {{ .Values.env.databaseUri | required "env.databaseUri must be set!" | b64enc }}
  FINERACT_USER: {{ .Values.env.FINERACT_USER | required "env.FINERACT_USER must be set!" | b64enc }}
  FINERACT_PASS: {{ .Values.env.FINERACT_PASS | required "env.FINERACT_PASS must be set!" | b64enc }}
