app:
  name: ucard-ng-auth-svc
  port: 5001
  image:
    repository: docker.io/crazydev0/ucard_ng_auth_svc
    tag: latest
    pullPolicy: Always
  migrations:
    image: docker.io/crazydev0/ucard_ng_auth_migration:latest
  replicas: 1
  namespace: ucard-ng-dev

dapr:
  appId: id-auth-svc
  appPort: 5001
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: 0.0.0.0

secret:
  name: ucard-ng-auth-svc-secret
  data:
    NODE_ENV: null
    DAPR_PUBSUB_NAME: null
    DB_USERNAME: null
    DB_PASSWORD: null
    DB_DATABASE: null
    DB_DATABASE_TYPE: null
    KEYCLOAK_REALM: null
    KEYCLOAK_ADMIN_USERNAME: null
    KEYCLOAK_ADMIN_PASSWORD: null
    PERMIFY_ENTITY_ID: null
    PERMIFY_TENANT_NAME: null

configmap:
  name: ucard-ng-auth-svc-secret
  data:
    DB_HOST: null
    APP_HOST: null
    APP_PORT: null
    DAPR_HTTP_PORT: null
    DB_PORT: null
    BASE_URL: null
    KEYCLOAK_BASE_URL: null
    PERMIFY_HTTP_URL: null
    PERMIFY_GRPC_URL: null
    UCARD_TOKEN_SVC_URL: null

service:
  type: ClusterIP
  protocol: TCP
