apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.app.name }}-db-migrate
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.app.migrations.image }}"
          imagePullPolicy: Always
          command: ["npm"]
          args: ["run", "typeorm:migrate"]
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
            - configMapRef:
                name: {{ .Values.configmap.name }}
